=== Robotics-Research-Group-KUL/crospi_application_template/skill_specifications/libraries/skill_library.schema.json
{
    "$schema":"http://json-schema.org/draft-06/schema",
    "$id":"skill_library.json",
    "title":"eTaSL skill specifications libraries",
    "type":"object",
    "description":"Libraries containing skills based on etasl task specifications",
    "required": ["name", "version","description","required_task_libs","authors","maintainers"],
    "properties": {
        "$schema" : {
            "type":"string"
        },
        "name":{
            "description": "Name of the library",
            "type":"string",
            "pattern": "^[a-zA-Z0-9_]+$"
        },
        "version":{
            "description": "Version of library",
            "type":"string",
            "pattern": "^(\\d+\\.){2}\\d+(-[a-zA-Z]+)?$",
            "default": "0.0.0",
            "examples": [
                "1.0.0-beta"
            ]
        },
        "description":{
            "description": "Text describing the purpose of the library",
            "type":"string"
        },
        "license":{
            "description": "",
            "type":"string",
            "examples":[
                "GNU GPLv3",
                "Apache License 2.0"
            ]
        },
        "required_task_libs": {
            "title":"List required task libraries",
            "description":"List of required task libraries that are needed to run the skills",
            "type" : "array",
            "items" : {
                "$ref" : "#/$defs/required_task_libs" 
            }
        },
        "authors": {
            "title":"List of authors",
            "description":"List of authors that participated on the development of the library",
            "type" : "array",
            "items" : {
                "$ref" : "#/$defs/author" 
            }
        },
        "maintainers": {
            "title":"List of maintainers",
            "description":"List of maintainers that currently maintain the library",
            "type" : "array",
            "items" : {
                "$ref" : "#/$defs/maintainer" 
            }
        },
        "acknowledgements":{
            "description": "acknowledgements to people who made contributions or to project funding",
            "type":"string"
        }
    },
    "$defs": {
        "required_task_libs": { 
            "title":"Required task libs",
            "type":"object",
            "description":"List of all the required task libraries with links to repos",
            "required": ["lib_name", "version","repo_url"],
            "properties": {
                "lib_name":{
                    "description": "Name of the required library",
                    "type":"string"
                },
                "version":{
                    "description": "Version of the required library",
                    "type":"string",
                    "pattern": "^(\\d+\\.){2}\\d+(-[a-zA-Z]+)?$",
                    "default": "0.0.0",
                    "examples": [
                        "1.0.0-beta"
                    ]
                },
                "repo_url":{
                    "description": "URL to a valid remote git repository (e.g. github, gitlab, etc)",
                    "type":"string",
                    "pattern": "^(https:\\/\\/|git@)([\\w.-]+)([:\\/])([\\w./-]+)(\\.git)?$",
                    "examples": [
                        "todo.git"
                    ]
                }
            }
        },
        "author": { 
            "title":"Author",
            "type":"object",
            "description":"Data of an author",
            "required": ["name", "affiliation","email"],
            "properties": {
                "name":{
                    "description": "Name of the author",
                    "type":"string"
                },
                "affiliation":{
                    "description": "Affiliation of the author",
                    "type":"string",
                    "default": "KU Leuven"
                },
                "email":{
                    "description": "Email of the author",
                    "type":"string",
                    "pattern": "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$",
                    "examples": [
                        "author_mail@gmail.com"
                    ]
                }
            }
        },
        "maintainer": { 
            "title":"Maintainer",
            "type":"object",
            "description":"Data of an maintainer",
            "required": ["name", "affiliation","email"],
            "properties": {
                "name":{
                    "description": "Name of the maintainer",
                    "type":"string"
                },
                "affiliation":{
                    "description": "Affiliation of the maintainer",
                    "type":"string",
                    "default": "KU Leuven"
                },
                "email":{
                    "description": "Email of the maintainer",
                    "type":"string",
                    "pattern": "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$",
                    "examples": [
                        "maintainer_mail@gmail.com"
                    ]
                }
            }
        }
    },
    "additionalProperties":false
}

=== Robotics-Research-Group-KUL/crospi_application_template/skill_specifications/libraries/pcb_insertion_lib/skill_library.json
{
    "$schema": "../skill_library.schema.json",
    "name": "psc_insertion_lib",
    "description": "TODO",
    "license": "GNU GPLv3",
    "version": "0.1.0",
    "required_task_libs": [
        {
            "lib_name": "core_task_lib",
            "repo_url": "git@gitlab.kuleuven.be:todo.git",
            "version": "0.0.0"
        },
        {
            "lib_name": "insertions_lib",
            "repo_url": "git@gitlab.kuleuven.be:todo.git",
            "version": "0.0.0"
        }
    ],
    "authors": [
        {
            "name": "Federico Ulloa Rios",
            "affiliation": "KU Leuven",
            "email": "federico.ulloarios@kuleuven.be"
        }
    ],
    "maintainers": [
        {
            "name": "Federico Ulloa Rios",
            "affiliation": "KU Leuven",
            "email": "federico.ulloarios@kuleuven.be"
        }
    ],
    "acknowledgements": "The authors acknowledge the financial support of EU project AI-Prism (TODO)"
}

=== Robotics-Research-Group-KUL/crospi_application_template/skill_specifications/libraries/mav_control_lib/skill_library.json
{
    "$schema": "../skill_library.schema.json",
    "name": "cable_routing_lib",
    "description": "Library with task specifications for cable routing",
    "license": "GNU GPLv3",
    "version": "0.1.0",
    "required_task_libs": [
        {
            "lib_name": "mav_control_lib",
            "repo_url": "git@gitlab.kuleuven.be:todo.git",
            "version": "0.0.0"
        }
    ],
    "authors": [
        {
            "name": "Federico Ulloa Rios",
            "affiliation": "KU Leuven",
            "email": "federico.ulloarios@kuleuven.be"
        }
    ],
    "maintainers": [
        {
            "name": "Federico Ulloa Rios",
            "affiliation": "KU Leuven",
            "email": "federico.ulloarios@kuleuven.be"
        }
    ],
    "acknowledgements": "The authors acknowledge the financial support of EU project AI-Prism (TODO)"
}

=== Robotics-Research-Group-KUL/crospi_application_template/skill_specifications/libraries/robelix/skill_library.json
{
    "$schema": "../skill_library.schema.json",
    "name": "robelix",
    "description": "Skill library for robelix",
    "license": "GNU GPLv3",
    "version": "0.1.0",
    "required_task_libs": [
        {
            "lib_name": "core_task_lib",
            "repo_url": "git@gitlab.kuleuven.be:todo.git",
            "version": "0.0.0"
        }
    ],
    "authors": [
        {
            "name": "Santiago Iregui",
            "affiliation": "KU Leuven",
            "email": "santiago.iregui@kuleuven.be"
        }
    ],
    "maintainers": [
        {
            "name": "Santiago Iregui",
            "affiliation": "KU Leuven",
            "email": "santiago.iregui@kuleuven.be"
        }
    ],
    "acknowledgements": "The authors acknowledge the financial support of EU project AI-Prism (TODO)"
}

=== Robotics-Research-Group-KUL/crospi_application_template/skill_specifications/libraries/peg_insertions_robelix/skill_library.json
{
    "$schema": "../skill_library.schema.json",
    "name": "peg_insertions_robelix",
    "description": "Skill library for peg_insertions_robelix",
    "license": "GNU GPLv3",
    "version": "0.1.0",
    "required_task_libs": [
        {
            "lib_name": "core_task_lib",
            "repo_url": "git@gitlab.kuleuven.be:todo.git",
            "version": "0.0.0"
        }
    ],
    "authors": [
        {
            "name": "Santiago Iregui",
            "affiliation": "KU Leuven",
            "email": "santiago.iregui@kuleuven.be"
        },
        {
            "name": "Federico Ulloa",
            "affiliation": "KU Leuven",
            "email": "federico.ulloarios@kuleuven.be"
        }
    ],
    "maintainers": [
        {
            "name": "Santiago Iregui",
            "affiliation": "KU Leuven",
            "email": "santiago.iregui@kuleuven.be"
        },
        {
            "name": "Federico Ulloa",
            "affiliation": "KU Leuven",
            "email": "federico.ulloarios@kuleuven.be"
        }
    ],
    "acknowledgements": "The authors acknowledge the financial support of EU project AI-Prism (TODO)"
}
